### ISSUE TITLE
App review checklist

### ISSUE THREAD

**Issue by morgans3** [morgans3/NHS_Business_Intelligence_Platform_App#11]
- [ ] eslinting rules
- [ ] hardcoded URLs
- [ ] repeated components
- [ ] repeated functions
- [ ] remove all unused components, interfaces, guards, services
- [ ] remove all css/scss files that are empty
- [ ] split Covid-19 app
- [ ] test all pages
- [ ] test all api endpoints
- [ ] review UI flow through site
- [ ] review Styles through site
- [ ] can configuration(s) be moved to database?
- [ ] can components be moved to npm library?
- [ ] any duplicate component selectors? or component class names?
- [ ] review state management
- [ ] are same API calls being frequently used?
- [ ] are there API calls not being used?
- [ ] response handling for non-200 api responses?
- [ ] cypress test coverage? => new tasklist?
- [ ] documentation coverage/accuracy? => new tasklist?

**Comment by morgans3** [comment]
## Review of code using npx unimported:

### 11 unused dependencies
   1 │ @coachcare/datepicker
   2 │ @fortawesome/fontawesome-free
   3 │ @types/chart.js
   4 │ animate.css
   5 │ classlist.js
   6 │ compodoc
   7 │ core-js
   8 │ cy2
   9 │ leaflet-sidebar-v2
  10 │ ng-gallery
  11 │ web-animations-js

### 48 unimported files
1 │ /src/app/_models/chart_colour_ranges.ts
   2 │ /src/app/_models/excel.interface.ts
   3 │ /src/app/_models/mapping.interface.ts
   4 │ /src/app/_models/mosaiccode.ts
   5 │ /src/app/_models/SPI_Lookups.ts
   6 │ /src/app/applications/covid_intelligence/default/UserValidation/dialogvalidate.ts
   7 │ /src/app/applications/covid_intelligence/default/UserValidation/dialogverifiy.ts
   8 │ /src/app/applications/covid_intelligence/default/UserValidation/UserValidation.component.ts
   9 │ /src/app/applications/geosegmentation/_models/DTOCategories.ts
  10 │ /src/app/applications/geosegmentation/_models/DTOFormAnswer.ts
  11 │ /src/app/applications/geosegmentation/_models/DTOListItem.ts
  12 │ /src/app/applications/geosegmentation/_models/DTOSysAdmins.ts
  13 │ /src/app/applications/geosegmentation/_models/FeatureCollection.ts
  14 │ /src/app/applications/geosegmentation/_models/field.interface.ts
  15 │ /src/app/applications/geosegmentation/_models/FormState.interface.ts
  16 │ /src/app/applications/geosegmentation/_models/GSI.ts
  17 │ /src/app/applications/geosegmentation/_models/ModelApplication.ts
  18 │ /src/app/applications/geosegmentation/_models/ModelAppSettings.ts
  19 │ /src/app/applications/geosegmentation/_models/ModelEnviroment.ts
  20 │ /src/app/applications/geosegmentation/_models/ModelForms.ts
  21 │ /src/app/applications/geosegmentation/_models/ModelOrganisation.ts
  22 │ /src/app/applications/geosegmentation/_models/ModelOTPToken.ts
  23 │ /src/app/applications/geosegmentation/_models/ModelRefreshTokenReq.ts
  24 │ /src/app/applications/geosegmentation/_models/ModelUser.ts
  25 │ /src/app/applications/geosegmentation/_models/notifications.ts
  26 │ /src/app/applications/geosegmentation/_models/OptGroup.ts
  27 │ /src/app/applications/geosegmentation/_models/PageEntities.ts
  28 │ /src/app/applications/geosegmentation/_models/result.interface.ts
  29 │ /src/app/applications/geosegmentation/_models/SystemAlerts.ts
  30 │ /src/app/applications/geosegmentation/_models/tasks.ts
  31 │ /src/app/applications/geosegmentation/_services/context.service.ts
  32 │ /src/app/applications/geosegmentation/_services/data.service.ts
  33 │ /src/app/applications/geosegmentation/_services/forms.service.ts
  34 │ /src/app/applications/geosegmentation/shared/components/_models/chart.ts
  35 │ /src/app/applications/place_based/_components/stat-card.component.ts
  36 │ /src/app/applications/place_based/Landing/Landing.component.ts
  37 │ /src/app/applications/population_health/pages/population-slicer/leaflet/leafletBubbleJp.ts
  38 │ /src/app/applications/population_health/pages/population-slicer/leaflet/leafletChoropleth.ts
  39 │ /src/app/material-component/material.module.ts
  40 │ /src/app/pages/stores/stores.module.ts
  41 │ /src/app/pages/stores/stores.routing.ts
  42 │ /src/app/pages/stores/stores/stores.component.ts
  43 │ /src/assets/styles/icons/font-awesome/font-awesome/attribution.js
  44 │ /src/assets/styles/icons/themify-icons/ie7/ie7.js
  45 │ /src/environments/environment.prod.ts
  46 │ /src/main.ts
  47 │ /src/polyfills.ts
  48 │ /src/test.ts

**Comment by morgans3** [comment]
Compilation errors (looks like some of those unimported files are being imported):

./src/app/applications/health_inequalities/pages/data/Data.component.ts - Warning: There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.

./src/app/applications/health_inequalities/pages/landing/Landing.component.ts - Warning: There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.

./src/app/applications/geosegmentation/pages/gsi/GSI/GSI.component.ts:6:0-31 - Error: Module not found: Error: Can't resolve 'leaflet.markercluster' in 'D:\inetpub\Github\NHS_Github\NHS_Business_Intelligence_Platform_App\src\app\applications\geosegmentation\pages\gsi\GSI'

./src/app/applications/suicide_prevention/default/Landing/Landing.component.ts:39:0-85 - Error: Module not found: Error: Can't resolve 'src/app/_models/chart_colour_ranges' in 'D:\inetpub\Github\NHS_Github\NHS_Business_Intelligence_Platform_App\src\app\applications\suicide_prevention\default\Landing'

./src/app/applications/suicide_prevention/default/Landing/Landing.component.ts:42:0-73 - Error: Module not found: Error: Can't resolve 'src/app/_models/mosaiccode' in 'D:\inetpub\Github\NHS_Github\NHS_Business_Intelligence_Platform_App\src\app\applications\suicide_prevention\default\Landing'

./src/assets/styles/style.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected expression.
     ╷
1221 │         @if length($transition) === 0 {
     │                                   ^
     ╵
  src\assets\styles\_custom.scss 1221:35  @import
  src\assets\styles\style.scss 25:9       root stylesheet

./node_modules/@asymmetrik/ngx-leaflet-markercluster/fesm2015/asymmetrik-ngx-leaflet-markercluster.mjs:6:0-31 - Error: Module not found: 
Error: Can't resolve 'leaflet.markercluster' in 'D:\inetpub\Github\NHS_Github\NHS_Business_Intelligence_Platform_App\node_modules\@asymmetrik\ngx-leaflet-markercluster\fesm2015'

Error: src/app/applications/covid_intelligence/default/patient/theograph/theograph.component.ts:176:22 - error TS2339: Property 'transition' does not exist on type 'Selection<any, unknown, null, undefined>'.

176                     .transition()
                         ~~~~~~~~~~
Error: src/app/applications/covid_intelligence/default/patient/theograph/theograph.component.ts:192:35 - error TS2339: Property 'transition' does not exist on type 'Selection<any, unknown, null, undefined>'.

192                 d3.select(t1[me]).transition().style("fill-opacity", "1").attr("height", this.admissionBarWidth).style("stroke", "none");
                                      ~~~~~~~~~~
Error: src/app/applications/covid_intelligence/default/patient/theograph/theograph.component.ts:245:22 - error TS2339: Property 'transition' does not exist on type 'Selection<any, unknown, null, undefined>'.

245                     .transition()
                         ~~~~~~~~~~
Error: src/app/applications/covid_intelligence/default/patient/theograph/theograph.component.ts:262:35 - error TS2339: Property 'transition' does not exist on type 'Selection<any, unknown, null, undefined>'.

262                 d3.select(t1[me]).transition().style("fill-opacity", 1).attr("r", this.admissionCircleRadius).style("stroke", "none");
                                      ~~~~~~~~~~
Error: src/app/applications/covid_intelligence/default/patient/theograph/theograph.component.ts:273:22 - error TS2339: Property 'transition' does not exist on type 'Selection<any, unknown, null, undefined>'.

273                     .transition()
                         ~~~~~~~~~~
Error: src/app/applications/geosegmentation/pages/gsi/GSI/GSI.component.html:135:21 - error NG8001: 'app-map' is not a known element:
1. If 'app-map' is an Angular component, then verify that it is part of this module.
2. If 'app-map' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

135                     <app-map
                        ~~~~~~~~
136                         [hidden]="!MosaicMapTwo && mapTwoStyle.display !== 'block'"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
143                         [rerender]="mapTwoRender"
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
144                     ></app-map>
    ~~~~~~~~~~~~~~~~~~~~~
  src/app/applications/geosegmentation/pages/gsi/GSI/GSI.component.ts:29:18
    29     templateUrl: "./GSI.component.html",
                        ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component GSIComponent.

Error: src/app/applications/geosegmentation/pages/gsi/GSI/GSI.component.html:137:25 - error NG8002: Can't bind to 'MapData' since it isn't a known property of 'app-map'.
1. If 'app-map' is an Angular component and it has 'MapData' input, then verify that it is part of this module.
2. If 'app-map' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.


137                         [MapData]="MosaicMapTwo"
                            ~~~~~~~~~~~~~~~~~~~~~~~~
  src/app/applications/geosegmentation/pages/gsi/GSI/GSI.component.ts:29:18
    29     templateUrl: "./GSI.component.html",
                        ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component GSIComponent.


Error: src/app/applications/geosegmentation/pages/gsi/GSI/GSI.component.html:141:25 - error NG8002: Can't bind to 'MapZoom' since it isn't a known property of 'app-map'.
1. If 'app-map' is an Angular component and it has 'MapZoom' input, then verify that it is part of this module.
2. If 'app-map' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

141                         [MapZoom]="MapTwoZoom"
                            ~~~~~~~~~~~~~~~~~~~~~~
  src/app/applications/geosegmentation/pages/gsi/GSI/GSI.component.ts:29:18
    29     templateUrl: "./GSI.component.html",
                        ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component GSIComponent.


Error: src/app/applications/geosegmentation/pages/gsi/GSI/GSI.component.html:142:25 - error NG8002: Can't bind to 'MapCenter' since it isn't a known property of 'app-map'.
1. If 'app-map' is an Angular component and it has 'MapCenter' input, then verify that it is part of this module.
2. If 'app-map' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

142                         [MapCenter]="MapTwoCenter"
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~
  src/app/applications/geosegmentation/pages/gsi/GSI/GSI.component.ts:29:18
    29     templateUrl: "./GSI.component.html",
                        ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component GSIComponent.


Error: src/app/applications/geosegmentation/pages/gsi/GSI/GSI.component.html:143:25 - error NG8002: Can't bind to 'rerender' since it isn't a known property of 'app-map'.
1. If 'app-map' is an Angular component and it has 'rerender' input, then verify that it is part of this module.
2. If 'app-map' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

143                         [rerender]="mapTwoRender"
                            ~~~~~~~~~~~~~~~~~~~~~~~~~
  src/app/applications/geosegmentation/pages/gsi/GSI/GSI.component.ts:29:18
    29     templateUrl: "./GSI.component.html",
                        ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component GSIComponent.

Error: src/app/applications/geosegmentation/pages/gsi/mosaic-key/mosaic-key.component.ts:155:33 - error TS2339: Property 'transition' does not exist on type 'Selection<any, unknown, null, undefined>'.

155                 d3.select(this).transition().duration(500).style("y", 0).style("height", height);
                                    ~~~~~~~~~~
Error: src/app/applications/place_based/mapping/mapping/mapping.component.ts:5:45 - error TS2307: Cannot find module 'src/app/_models/mapping.interface' or its corresponding type declarations.

5 import { iMapData, iMappingDashboard } from "src/app/_models/mapping.interface";
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/place_based/mapping/mapping/panels/mapdatasets/mapdatasets.component.ts:2:32 - error TS2307: Cannot find module 'src/app/_models/excel.interface' or its corresponding type declarations.


2 import { iExcelWorkBook } from "src/app/_models/excel.interface";
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: src/app/applications/population_health/pages/cohortcompare/cohortcompare.component.ts0m:93:29 - error TS2339: Property 'getCohortsByUsername' does not exist on type 'APIService'.

93             this.apiService.getCohortsByUsername({ username: this.tokenDecoded.username }).subscribe((res: Cohort[]) => {
                               ~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/population_health/pages/intervention-assistant/intervention-assistant.component.ts:81:18 - error TS2339: Property 'getCohortsByUsername' does not exist on type 'APIService'.

81                 .getCohortsByUsername({
                    ~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/population_health/pages/need-list/need-list.component.ts:1409:18 - error TS2339: Property 'getCohortsByUsername' does not exist on type 'APIService'.

1409                 .getCohortsByUsername({
                      ~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/population_health/pages/population-slicer/cohort-all/cohort-all.component.ts:49:18 - error TS2339: Property 'getCohortsByUsername' does not exist on type 'APIService'.

49                 .getCohortsByUsername({
                    ~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/population_health/pages/population-slicer/cohort-all/cohort-all.component.ts:164:25 - error TS2339: Property 'createCohort' does not exist on type 'APIService'.

164         this.apiService.createCohort(this.selectedCohort).subscribe(() => {
                            ~~~~~~~~~~~~
Error: src/app/applications/population_health/pages/population-slicer/cohort-all/cohort-all.component.ts:166:18 - error TS2339: Property 'getCohortsByUsername' does not exist on type 'APIService'.

166                 .getCohortsByUsername({
                     ~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/population_health/pages/population-slicer/cohort-all/cohort-all.component.ts:199:25 - error TS2339: Property 'updateCohort' does not exist on type 'APIService'.

199         this.apiService.updateCohort(this.selectedCohort).subscribe(() => {
                            ~~~~~~~~~~~~
Error: src/app/applications/population_health/pages/population-slicer/cohort-all/cohort-all.component.ts:201:18 - error TS2339: Property 'getCohortsByUsername' does not exist on type 'APIService'.

201                 .getCohortsByUsername({
                     ~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/population_health/pages/population-slicer/cohort-all/cohort-all.component.ts:227:37 - error TS2339: Property 'deleteCohort' does not exist on type 'APIService'.

227                     this.apiService.deleteCohort(this.selectedCohort).subscribe(() => {
                                        ~~~~~~~~~~~~
Error: src/app/applications/population_health/pages/population-slicer/cohort-all/cohort-all.component.ts:229:30 - error TS2339: Property 'getCohortsByUsername' does not exist on type 'APIService'.

229                             .getCohortsByUsername({
                                 ~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/suicide_prevention/default/Admin/Admin.component.ts:3:33 - error[90m TS2307: Cannot find module 'src/app/_models/SPI_Lookups' or its corresponding type declarations.

3 import { IncidentMethods } from "src/app/_models/SPI_Lookups";
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/suicide_prevention/default/Admin/Methods/Methods.component.ts:8:33 - error TS2307: Cannot find module 'src/app/_models/SPI_Lookups' or its corresponding type declarations.

8 import { IncidentMethods } from "src/app/_models/SPI_Lookups";
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/suicide_prevention/default/Incidents/IncidentForm/IncidentForm.component.ts:6:54 - error TS2307: Cannot find module 'src/app/_models/SPI_Lookups' or its corresponding type declarations.

6 import { iLocation, Incident, IncidentMethods } from "src/app/_models/SPI_Lookups";
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/suicide_prevention/default/Incidents/IncidentForm/findlocation/findlocation.component.ts:6:27 - error TS2307: Cannot find module 'src/app/_models/SPI_Lookups' or its corresponding type declarations.

6 import { iLocation } from "src/app/_models/SPI_Lookups";
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/suicide_prevention/default/Incidents/Incidents.component.ts:5:26 - error TS2307: Cannot find module 'src/app/_models/SPI_Lookups' or its corresponding type declarations.

5 import { Incident } from "src/app/_models/SPI_Lookups";
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/suicide_prevention/default/Landing/Landing.component.ts:9:48 - error TS2307: Cannot find module 'src/app/_models/chart_colour_ranges' or its corresponding type declarations.

9 import { colorbrewer, DeprivationColors } from "src/app/_models/chart_colour_ranges";
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/suicide_prevention/default/Landing/Landing.component.ts:15:30 - error TS2307: Cannot find module 'src/app/_models/SPI_Lookups' or its corresponding type declarations.

15 import { StatCardData } from "src/app/_models/SPI_Lookups";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/suicide_prevention/default/Landing/Landing.component.ts:16:45 - error TS2307: Cannot find module 'src/app/_models/mosaiccode' or its corresponding type declarations.

16 import { MosaicColours, MosaicDomain } from "src/app/_models/mosaiccode";
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/suicide_prevention/default/mapping/mapping/mapping.component.ts:10:32 - error TS2307: Cannot find module 'src/app/_models/excel.interface' or its corresponding type declarations.

10 import { iExcelWorkBook } from "src/app/_models/excel.interface";
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: src/app/applications/suicide_prevention/default/mapping/mapping/mapping.component.ts:11:35 - error TS2307: Cannot find module 'src/app/_models/mapping.interface' or its corresponding type declarations.

11 import { iMappingDashboard } from "src/app/_models/mapping.interface";
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error: src/app/layouts/full/full.component.html:31:52 - error TS2554: Expected 0 arguments, but got 1.

31                     (changeSidebar)="toggleSidebar($event)"
                                                      ~~~~~~
  src/app/layouts/full/full.component.ts:31:18
    31     templateUrl: "full.component.html",
                        ~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component FullComponent.


Error: src/app/pages/admin/users/user/user.component.ts:193:32 - error TS2345: Argument of type '{ teamcode: any; username: any; joindate: Date; }' is not assignable to parameter of type 'iTeamMembers'.
  Property '_id' is missing in type '{ teamcode: any; username: any; joindate: Date; }' but required in type 'iTeamMembers'.

193                 .addTeamMember({
                                   ~
194                     teamcode: $event.option.value.code,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
196                     joindate: new Date(),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
197                 })
    ~~~~~~~~~~~~~~~~~

  node_modules/diu-component-library/lib/_models/teams.interface.d.ts:16:5
    16     _id: string;
           ~~~
    '_id' is declared here.


Error: src/app/pages/admin/users/user/user.component.ts:216:35 - error TS2345: Argument of type '{ _id: any; }' is not assignable to parameter of type 'iTeamMembers'.
  Type '{ _id: any; }' is missing the following properties from type 'iTeamMembers': teamcode, username, joindate

216                 .removeTeamMember({
                                      ~
217                     _id: this.teams.selected[index].link_id,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
218                 })
    ~~~~~~~~~~~~~~~~~
